language: java

jdk:
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    secure: b6V2NZgMyTmsTBo27a8YdEY3ZdPBY6G+ZwEIEJP9/xUABpG967MhXarIGvryIWco4WTnYVQeubstQQHP6zkGRccWpYDRmXRng9e8MvzATzHS67Z1YTVX+I5PQIxBSoKi6QgJMSnvCVU2REhsSfVqHYguYZ5ZBkIy9QidBmu2VElE36aFKOzFG96jLCMLaniM3ASu+Mcf58M5QRVNEQf5qTHAGubYY0k5Joib9oxlph4q+8zfvozD5XSlwDe9Hxd8Vls+jvCgWBPvj7ydf8qjQHfmaO+KdIa/yjS+a5Y5ILnLvNFPRIAkZSwTuLhaoNCGeLCjydCsL+eN9wpys568FlKz3cJvhDocVypXMXRXxFY/UnNZEoByxdEhB099cgbmHaGwGDXjC5xT9xgNsW5f+VkO1yW5WbiQWXH4vrbbvI/tuhWA3NBSc9bMTGXxRvIR4t30CDYGqIh1Rp9h2oz8lMtlg01GsXpRmPE7dX4Ec97vSoh5T4ddn7CIb6s98UgdeR3XA2uuGSgdyP3qUGh9jqdQJO0BLvql+QHqZQylW9KTjkxzr4py+90P4660weG0swGHxUeoZYQnJPU7h1VSydXIFdl9iGBcsTy8faeG5bBdBjZzYqBkgML6/yjDNvw/4VT1K+aWaJGK0QVa5GrQ1x4KIWRTTxpVep4zcS425RA=
